/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null } |
  { 'noPreference' : null };
export interface Message {
  'id' : bigint,
  'text' : string,
  'receiverId' : string,
  'timestamp' : bigint,
  'senderId' : string,
}
export interface PaymentRequest {
  'studentId' : string,
  'stripePaymentId' : string,
  'tutorId' : string,
  'amount' : bigint,
}
export type TuitionType = { 'both' : null } |
  { 'offline' : null } |
  { 'online' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveTutor' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPayment' : ActorMethod<[PaymentRequest], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMessage' : ActorMethod<[bigint], [] | [Message]>,
  'getMessages' : ActorMethod<[string], Array<Message>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'postRequirement' : ActorMethod<
    [string, string, string, TuitionType, Gender, string],
    undefined
  >,
  'registerTutor' : ActorMethod<
    [
      string,
      string,
      Gender,
      Array<string>,
      Array<string>,
      TuitionType,
      string,
      bigint,
      string,
      [] | [string],
      boolean,
    ],
    undefined
  >,
  'sendMessage' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];