/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaymentRequest = IDL.Record({
  'studentId' : IDL.Text,
  'stripePaymentId' : IDL.Text,
  'tutorId' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'receiverId' : IDL.Text,
  'timestamp' : IDL.Int,
  'senderId' : IDL.Text,
});
export const TuitionType = IDL.Variant({
  'both' : IDL.Null,
  'offline' : IDL.Null,
  'online' : IDL.Null,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
  'noPreference' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveTutor' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPayment' : IDL.Func([PaymentRequest], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMessage' : IDL.Func([IDL.Nat], [IDL.Opt(Message)], ['query']),
  'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'postRequirement' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, TuitionType, Gender, IDL.Text],
      [],
      [],
    ),
  'registerTutor' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Gender,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        TuitionType,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Bool,
      ],
      [],
      [],
    ),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaymentRequest = IDL.Record({
    'studentId' : IDL.Text,
    'stripePaymentId' : IDL.Text,
    'tutorId' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'receiverId' : IDL.Text,
    'timestamp' : IDL.Int,
    'senderId' : IDL.Text,
  });
  const TuitionType = IDL.Variant({
    'both' : IDL.Null,
    'offline' : IDL.Null,
    'online' : IDL.Null,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
    'noPreference' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveTutor' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPayment' : IDL.Func([PaymentRequest], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMessage' : IDL.Func([IDL.Nat], [IDL.Opt(Message)], ['query']),
    'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'postRequirement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, TuitionType, Gender, IDL.Text],
        [],
        [],
      ),
    'registerTutor' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Gender,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          TuitionType,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Bool,
        ],
        [],
        [],
      ),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };